import fs from 'fs';

function generateNFTContent() {
    // Erstelle das nfts Verzeichnis, falls es nicht existiert
    if (!fs.existsSync('./nfts')){
        fs.mkdirSync('./nfts');
    }
    
    const earnings = Math.random() * 0.01;
    const nft = {
        name: "AutoNFT-" + Date.now(),
        description: "Generated by AETHEL·PRIME Live",
        earnings: earnings.toFixed(8) // Simuliere Einnahmen in einer kleinen Kryptowährung
    };
    
    const filePath = `./nfts/${nft.name}.json`;
    fs.writeFileSync(filePath, JSON.stringify(nft, null, 2));
    
    // Ausgabe als JSON, damit der Python-Orchestrator es parsen kann
    console.log(JSON.stringify(nft));
    
    return nft;
}

generateNFTContent();
